title: Minh's Personal Website
description: Personal website for blogging and showcasing projects.
baseurl: "/Personal_Website"
url: "https://minhnguyen2xx6.github.io" # the base hostname & protocol for your site
